# profile puppetboard
# @param secret_key - the secret key for puppetboard, can be generated by `openssl rand -hex 32`
class profile::puppetboard (
  String $secret_key,
) {
  # Configure Apache on this server
  class { 'apache':
    default_vhost => false,
  }
  class { 'apache::mod::status':
    requires => 'ip 127.0.0.1 ::1 10.21.2.0/24',
  }

# Configure Puppetboard
# SSL certificates are required when puppetboard and
# puppetdb run on separate hosts. SEE ->README.md!!!
  $ssl_dir = '/etc/pki/tls'
  file { "${ssl_dir}/private/${facts['networking']['fqdn']}.pem":
    ensure => file,
    mode   => '0644',
    group  => apache,
    source => "/etc/puppetlabs/puppet/ssl/private_keys/${facts['networking']['fqdn']}.pem",
  }
  file { "${ssl_dir}/certs/${facts['networking']['fqdn']}.pem":
    ensure => file,
    mode   => '0644',
    group  => apache,
    source => "/etc/puppetlabs/puppet/ssl/certs/${facts['networking']['fqdn']}.pem",
  }
  file { "${ssl_dir}/certs/ca.pem":
    ensure => file,
    mode   => '0644',
    source => '/etc/puppetlabs/puppet/ssl/certs/ca.pem',
  }

  class { 'puppetboard':
    python_version      => '3.9',
    secret_key          => $secret_key,
    manage_virtualenv   => true,
    puppetdb_host       => 'db.preda.ca',
    puppetdb_port       => 8081,
    puppetdb_key        => "${ssl_dir}/private/${facts['networking']['fqdn']}.pem",
    puppetdb_ssl_verify => "${ssl_dir}/certs/ca.pem",
    puppetdb_cert       => "${ssl_dir}/certs/${facts['networking']['fqdn']}.pem",
    manage_selinux      => true,
  }

  class { 'puppetboard::apache::vhost':
    vhost_name => 'web.preda.ca',
    port       => 443,
    ssl        => true,
    ssl_cert   => "${ssl_dir}/certs/${facts['networking']['fqdn']}-cert.pem",
    ssl_key    => "${ssl_dir}/private/${facts['networking']['fqdn']}-key.pem",
    ssl_chain  => "${ssl_dir}/certs/${facts['networking']['fqdn']}-chain.pem",
  }
  # change selinux context as follows, otherwise, loading ppboard will throw error 403
  selinux::fcontext { '/srv/puppetboard(/.*)?':
    seltype => 'httpd_sys_content_t',
  }

  selinux::fcontext { '/srv/puppetboard/virtenv-puppetboard/bin(/.*)?':
    seltype => 'httpd_sys_script_exec_t',
  }

  exec { 'restorecon-puppetboard':
    command     => '/sbin/restorecon -Rv /srv/puppetboard',
    refreshonly => true,
    subscribe   => [
      Selinux::Fcontext['/srv/puppetboard(/.*)?'],
      Selinux::Fcontext['/srv/puppetboard/virtenv-puppetboard/bin(/.*)?'],
    ],
  }
}
